[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.3.0"
simple-websockets = "0.1.6"
tokio = { version = "1.29.1", features = ["full"] }
