apiVersion: apps/v1
kind: Deployment
metadata:
  name: warfrost-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warfrost
  template:
    metadata:
      name: warfrost-backend-pod
      labels:
        app: warfrost
    spec:
      containers:
        - name: warfrost-backend
          image: warfrost-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
